/* Historia y patrimonio de Tossa. Textos resumidos y redactados por Paradis Blau a partir de la información de Tossa Turisme (visittossa.com);
   los datos prácticos (dirección, horario, teléfono, precio) son los que publica Turisme a fecha de consulta (05/10/2026) y pueden cambiar.
   Campos: t, tag, r (resumen), d (datos prácticos), mapa (id del punto del mapa), u (ficha en Turisme), foto. */
window.PATRIMONIO = [
  { id: "tiempo", titulo: "Tossa a través del tiempo", intro: "Tossa es un museo al aire libre: huellas prehistóricas, una Turissa romana, una villa medieval amurallada y un pueblo que fue refugio de artistas.", items: [
    { t: "Prehistoria", tag: "Megalitos", r: "Hay menhires y dólmenes en el macizo de Ardenya-Cadiretes. La ruta megalítica empieza en el Santuario de Sant Grau.", u: "https://visittossa.com/es/patrimonio-cultural/tossa-a-traves-del-tiempo/prehistoria/" },
    { t: "Villa romana dels Ametllers", tag: "Siglos I a.C. – V d.C.", r: "Una de las villas romanas más importantes de la antigua provincia Tarraconense, dedicada al vino. Se conservan termas, mosaicos y un ninfeo; las piezas más valiosas están en el Museo Municipal.",
      d: ["Av. del Pelegrí 5–13", "Horarios de visita: Casa de Cultura, +34 972 340 905"], mapa: "ametllers", u: "https://visittossa.com/es/patrimonio-cultural/tossa-a-traves-del-tiempo/epoca-romana/", foto: "/assets/patrimonio/ametllers.jpg", pos: "50% 50%", credito: { a: "Shesmax", l: "CC BY-SA 4.0", u: "https://commons.wikimedia.org/wiki/File:Tossa_de_Mar._Roman_Villa_of_Ametllers_-_005.jpg" } },
    { t: "La Vila Vella", tag: "Siglo XIII · Monumento desde 1931", r: "El recinto amurallado es el emblema de Tossa y el único pueblo medieval fortificado que se conserva en el litoral catalán. Tiene torres como la de en Joanàs, la de les Hores y la del Codolar, calles empedradas, la antigua iglesia gótica de Sant Vicenç y el faro, que ocupa el lugar del antiguo castillo.",
      d: ["C/ Portal · Abierto todo el año, 24 horas · Acceso gratuito"], mapa: "muralles", foto: "/assets/foto-muralles.jpg", u: "https://visittossa.com/es/patrimonio-cultural/tossa-a-traves-del-tiempo/el-recinto-amurallado-de-la-vila-vella/" },
    { t: "Tossa, villa marinera", tag: "Identidad marinera", r: "Tossa forma parte de la marca Barrios y Villas Marineras de Cataluña desde 2019. Su carácter marinero se ve en el faro, las murallas, la capilla del Socorro, las antiguas pescaderías y Can Ganga, y también en su cocina, con platos de barca como el «cim i tomba».", u: "https://visittossa.com/es/patrimonio-cultural/tossa-a-traves-del-tiempo/tossa-villa-marinera/" },
    { t: "Barrio de Sa Roqueta", tag: "Siglo XVI", r: "El antiguo barrio de pescadores junto a la playa d'Es Codolar: callejones sin coches, escaleras, rincones floridos y casas singulares como Can Ganga.", d: ["Entre las calles Estolt y Portal"], u: "https://visittossa.com/es/patrimonio-cultural/tossa-a-traves-del-tiempo/barrio-de-sa-roqueta/" },
    { t: "Iglesia parroquial de Sant Vicenç", tag: "Neoclásica, 1755", r: "Se construyó cuando la iglesia de la Vila Vella se quedó pequeña. Es un edificio sencillo, con una nave central muy destacada.", d: ["Plaza de l'Església"], mapa: "esg-sant-vicenc", u: "https://visittossa.com/es/patrimonio-cultural/tossa-a-traves-del-tiempo/iglesia-parroquial/", foto: "/assets/patrimonio/esglesia.jpg", pos: "50% 50%", credito: { a: "Enric", l: "CC BY-SA 4.0", u: "https://commons.wikimedia.org/wiki/File:116_Esgl%C3%A9sia_de_Sant_Vicen%C3%A7_(Tossa_de_Mar).jpg" } },
    { t: "Capilla dels Socors", tag: "1593", r: "Capilla de origen marinero, levantada por un patrón agradecido a la Virgen del Socorro tras salvarse de un naufragio. Está ligada a fiestas, como el baile «toquen a córrer», y a la tradición del Pelegrí.", d: ["Calle dels Socors"], mapa: "socors", u: "https://visittossa.com/es/patrimonio-cultural/tossa-a-traves-del-tiempo/capilla-dels-socors/", foto: "/assets/patrimonio/socors.jpg", pos: "50% 50%", credito: { a: "Tanya Dedyukhina", l: "CC BY 3.0", u: "https://commons.wikimedia.org/wiki/File:Tossa_De_Mar_-_panoramio_(5).jpg" } },
    { t: "Casa de Cultura", tag: "Antiguo hospital, 1773", r: "El antiguo Hospital de San Miguel, fundado por Tomàs Vidal, que volvió rico de América y lo dejó para un hospital de caridad. Tiene un claustro y una capilla barroca.", d: ["Av. del Pelegrí 8"], mapa: "casa-cultura", u: "https://visittossa.com/es/patrimonio-cultural/tossa-a-traves-del-tiempo/casa-de-cultura/", foto: "/assets/patrimonio/casa-cultura.jpg", pos: "50% 40%", credito: { a: "Google Street View (nov. 2022)", l: "captura ilustrativa", u: "https://www.google.com/maps" } },
    { t: "Casa Sans", tag: "Modernista, 1906", r: "Edificio ecléctico del arquitecto Antoni de Falguera, con gárgolas modernistas, mosaicos y vitrales. Hoy es un hotel privado.", d: ["Plaza d'Espanya 6 / Passeig de Mar 41"], u: "https://visittossa.com/es/patrimonio-cultural/tossa-a-traves-del-tiempo/casa-sans/", foto: "/assets/patrimonio/casa-sans.jpg", pos: "50% 30%", credito: { a: "Kent Wang", l: "CC BY-SA 4.0", u: "https://commons.wikimedia.org/wiki/File:Casa_Sans,_Tossa_de_Mar_01.jpg" } },
    { t: "Santuario de Sant Grau", tag: "A unos 15 km de Tossa", r: "Santuario ligado a la leyenda de San Gerardo de Aurillac, con un gran ábside semicircular. Cada 13 de octubre se celebra allí una romería.", d: ["GI-682 hacia Sant Feliu y después GIP-6821 hacia Llagostera"], u: "https://visittossa.com/es/patrimonio-cultural/tossa-a-traves-del-tiempo/santuario-de-sant-grau/", foto: "/assets/patrimonio/sant-grau.jpg", pos: "50% 55%", credito: { a: "Google Street View (abr. 2025)", l: "captura ilustrativa", u: "https://www.google.com/maps" } }
  ] },
  { id: "arte", titulo: "Arte y cultura", intro: "Los museos y el patrimonio artístico de Tossa, fruto de generaciones de tossenses y de los artistas que pasaron por aquí.", items: [
    { t: "Museo Municipal", tag: "Primer museo de arte contemporáneo del Estado, 1935", r: "Está en la antigua casa del gobernador de la Vila Vella. Guarda piezas de la villa romana y una colección de arte ligada a los artistas de vanguardia que se instalaron en Tossa en los años treinta, como Chagall o Masson.",
      d: ["Plaza Roig i Soler 1 (Vila Vella) · +34 972 340 709", "Cerrado por reformas, según Tossa Turisme (octubre 2026): conviene comprobarlo antes de ir"], mapa: "museu", u: "https://visittossa.com/es/patrimonio-cultural/arte-y-cultura/museo-municipal/" },
    { t: "Museo de la Mujer (Can Ganga)", tag: "Abierto en 2020", r: "Cuenta cómo era la vida en Tossa antes del turismo desde el papel de la mujer: la pesca, el hogar y el campo. Está en una masía fortificada del siglo XVI, con una fresquera excavada en la roca.",
      d: ["C/ Codolar 4", "Cierres anunciados por Turisme: 13 y 14 de octubre"], mapa: "dona", u: "https://visittossa.com/es/patrimonio-cultural/arte-y-cultura/museo-de-la-mujer/", foto: "/assets/patrimonio/can-ganga.jpg", pos: "50% 50%", credito: { a: "Mafoso (talk)", l: "CC BY-SA 3.0", u: "https://commons.wikimedia.org/wiki/File:Can_Ganga-Tossa-02.JPG" } },
    { t: "Faro de Tossa", tag: "1917 · «Un siglo de señales marítimas»", r: "Construido en la parte más alta del cabo, es hoy un museo sobre la historia y la tecnología de los faros de la Costa Brava, con las mejores vistas del pueblo.",
      d: ["Paseo de Vila Vella", "Todos los días: 10:00–13:00 y 16:00–20:00", "Entrada: 3 € / 1,50 € · +34 972 343 359"], mapa: "far", u: "https://visittossa.com/es/patrimonio-cultural/arte-y-cultura/faro-de-tossa/", foto: "/assets/patrimonio/far.jpg", pos: "50% 50%", credito: { a: "Enric", l: "CC BY-SA 4.0", u: "https://commons.wikimedia.org/wiki/File:079_Far_de_Tossa_de_Mar.jpg" } },
    { t: "Patrimonio escultórico", tag: "Esculturas por el pueblo", r: "Tossa tiene esculturas repartidas por sus calles: Ava Gardner en la Vila Vella, la Pescadora del Peixeteries, la sirena de la plaza del Far, la diosa Minerva de Frederic Marès y otras. Turisme publica el mapa completo.",
      d: ["Entre otras: Bienvenida al visitante (plaza de les Nacions sense Estat), Ava Gardner (Passeig de Vila Vella), Diosa Minerva (Av. Sant Raimon de Penyafort), Poseidón y la ninfa Toosa (Av. Costa Brava)"], mapa: "ava", u: "https://visittossa.com/es/patrimonio-cultural/arte-y-cultura/patrimonio-escultorico/" }
  ] },
  { id: "fiestas", titulo: "Fiestas, tradiciones y leyendas", intro: "Lo que se celebra y se cuenta en Tossa a lo largo del año.", items: [
    { t: "Fiestas mayores", tag: "22 de enero y 29 de junio", r: "Tossa celebra dos: la de invierno, el 22 de enero por San Vicente, patrón de la parroquia, y la de verano, el 29 de junio por San Pedro, patrón de los pescadores.", u: "https://visittossa.com/es/patrimonio-cultural/fiestas-tradiciones-y-leyendas/fiestas-de-tossa/" },
    { t: "Corpus Christi", tag: "Jueves posterior a la Santísima Trinidad (mayo o junio)", r: "Con las calles del centro engalanadas con alfombras de flores y altares, y una procesión por la tarde.", u: "https://visittossa.com/es/patrimonio-cultural/fiestas-tradiciones-y-leyendas/fiestas-de-tossa/" },
    { t: "Romería de Sant Grau", tag: "13 de octubre", r: "La romería más popular de Tossa: se sube al santuario, hay misa, sardanas y comida al aire libre. Hoy mucha gente va en coche, aunque aún hay quien sube a pie.", u: "https://visittossa.com/es/patrimonio-cultural/fiestas-tradiciones-y-leyendas/fiestas-de-tossa/" },
    { t: "El Pelegrí", tag: "20 de enero", r: "Una tradición del siglo XV. Cumpliendo un voto del pueblo tras una peste, un peregrino sale de la capilla dels Socors hacia Santa Coloma de Farners y vuelve al día siguiente, con una procesión iluminada con teas junto a las murallas.", u: "https://visittossa.com/es/patrimonio-cultural/fiestas-tradiciones-y-leyendas/tradiciones-de-tossa/" },
    { t: "«Toquen a córrer, ses nou sardanes»", tag: "2 de julio", r: "Un baile típico, antecesor de la sardana, que alterna nueve sardanas cortas con un galope por la calle dels Socors. Recuerda la leyenda de la Virgen del Socorro y el niño Xixanet.", u: "https://visittossa.com/es/patrimonio-cultural/fiestas-tradiciones-y-leyendas/tradiciones-de-tossa/" },
    { t: "Leyendas de Tossa", tag: "Las brujas de la Vila Vella y Xixanet", r: "La más conocida cuenta cómo tres brujas convertidas en gatos negros usaban cada noche la barca de un pescador de Es Codolar para viajar a América. Otra, la de Xixanet i sa Mitja Cana, habla de un milagro de la Virgen del Socorro.", u: "https://visittossa.com/es/patrimonio-cultural/fiestas-tradiciones-y-leyendas/leyendas-de-tossa/" }
  ] }
];
